---
title: "Change the title of your report"
output:
  html_document:
    toc: yes
    self_containted: false
---  
<!-- The report is produced from
REPOSITORY: the-name-of-the-repository
BRANCH: the-name-of-the-branch
PATH: ../Reports/
-->

<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of only one directory.-->
```{r, echo=F, message=F} 
library(knitr)
opts_knit$set(root.dir='../')  #Don't combine this call with any other chunk -especially one that uses file paths.
```

<!-- Set the report-wide options, and point to the external script file. -->
```{r, echo=F, message=T}
require(knitr)
opts_chunk$set(
  results='show', # Set
  message = TRUE, # De
  comment = NA,   #   fau
  tidy = FALSE,   #     lts
#   fig.height = 4.8, # physical dimensions
#   fig.width = 6.5,  # of produced impage
  out.width = NULL, # how it looks in html document
  fig.path = 'figure_rmd_NameOfReport/', # where images from this report are stored
  dev = "png",
  dpi = 400 # resolution: dots per inch. Use 90 to develop, 300-400 to print. adjust
)
echoChunks <- FALSE
warningChunks<- FALSE
messageChunks<- FALSE
options(width=120) #So the output is 50% wider than the default.
read_chunk("../Reports/reportTemplate.R") # the file to which knitr calls for the chunks
```

```{r LoadPackages, echo=TRUE, message=FALSE, warning=FALSE}
```

```{r DeclareGlobals, echo=T, message=T, }
```

```{r LoadData, echo=T, message=F}
```

```{r LabelingFactorLevels, echo=T, message=F}
```

```{r FirstLook, echo=T, message=F}
```

```{r FirstGraph, echo=T, message=F}
```


<!-- attaches a child containing common links and references -->
```{r child, child = './LinksAndRefs.Rmd'}
```
